services:
  frontend:
    build: .
    ports:
      - '5173:5173'
    environment:
      - VITE_API_URL=${VITE_API_URL}
    networks:
      - tailsync-network
    restart: unless-stopped

networks:
  tailsync-network:
    external: true